# Generated by Django 4.2.7 on 2023-12-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_aothor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='aothor',
            new_name='author',
        ),
    ]
